-- Migration Phase 3: Create call_signals table for Push Notification webhooks
CREATE TABLE IF NOT EXISTS public.call_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id TEXT NOT NULL,
    caller_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (caller_id) REFERENCES public.users (id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES public.users (id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE public.call_signals ENABLE ROW LEVEL SECURITY;

-- Policies for RLS
CREATE POLICY "Allow select call_signals" ON public.call_signals
    FOR SELECT USING (true);

CREATE POLICY "Allow insert call_signals" ON public.call_signals
    FOR INSERT WITH CHECK (true);

-- Enable Realtime
ALTER TABLE public.call_signals REPLICA IDENTITY FULL;
