-- Migration Phase 3: Add deadline submissions table for persistence
CREATE TABLE IF NOT EXISTS deadline_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deadline_id BIGINT REFERENCES deadlines(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    user_name VARCHAR(255) NOT NULL,
    user_initial VARCHAR(10) NOT NULL,
    note TEXT DEFAULT NULL,
    file_name VARCHAR(255) DEFAULT NULL,
    file_data TEXT DEFAULT NULL,
    images JSONB DEFAULT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    grade NUMERIC DEFAULT NULL,
    feedback TEXT DEFAULT NULL,
    graded_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    UNIQUE (deadline_id, user_id)
);

-- Enable RLS
ALTER TABLE deadline_submissions ENABLE ROW LEVEL SECURITY;

-- Add RLS Policies
DROP POLICY IF EXISTS "Allow public read deadline_submissions" ON deadline_submissions;
CREATE POLICY "Allow public read deadline_submissions" ON deadline_submissions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow insert deadline_submissions" ON deadline_submissions;
CREATE POLICY "Allow insert deadline_submissions" ON deadline_submissions FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update deadline_submissions" ON deadline_submissions;
CREATE POLICY "Allow update deadline_submissions" ON deadline_submissions FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow delete deadline_submissions" ON deadline_submissions;
CREATE POLICY "Allow delete deadline_submissions" ON deadline_submissions FOR DELETE USING (true);

-- Grant permissions to sequences and tables
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON deadline_submissions TO anon, authenticated;
